INSERT INTO releases (release_year, release_brand, release_name, category_id, subcategory_id, description) VALUES (2005, 'Topps', 'Series 1', 1, 1, 'First series of Topps flagship release for baseball.');

INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, '', 1, FALSE, NULL, 'Base cards for 2025 Topps Baseball Series 1');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Rainbow Foilboard', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Diamante Foil', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Holiday', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Holo Foil', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Sandglitter', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Silver Cracked Foilboard', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Spring Training', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Tin Variations', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Topps Foil Pattern', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Pink Diamante Foil', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Eggs', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Pink Holo Foil', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Rabbit', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Gold', 2, FALSE, 2025, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Aqua Holo Foil', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Aqua Rainbow Foil', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Team Color', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'True Photo', 2, FALSE, NULL, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Purple Holo Foil', 2, FALSE, 250, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Purple Rainbow', 2, FALSE, 250, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Blue Holo Foil', 2, FALSE, 150, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Blue Rainbow', 2, FALSE, 150, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Green Holo Foil', 2, FALSE, 99, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Green Rainbow', 2, FALSE, 99, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Spring Training Green Foilboard', 2, FALSE, 99, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Vintage Stock Retro', 2, FALSE, 99, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Independence Day', 2, FALSE, 76, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Canvas', 2, FALSE, 50, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Gold Diamante', 2, FALSE, 50, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Flowers', 2, FALSE, 50, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Gold Holo Foil', 2, FALSE, 50, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Gold Rainbow', 2, FALSE, 50, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Spring Training Gold Diamante', 2, FALSE, 50, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Orange Diamante', 2, FALSE, 25, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Memorial Day Camp', 2, FALSE, 25, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Orange Holo Foil', 2, FALSE, 25, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Orange Rainbow', 2, FALSE, 25, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Spring Training Orange Foilboard', 2, FALSE, 25, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Wood', 2, FALSE, 25, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Black Diamante', 2, FALSE, 10, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Black Holo Foil', 2, FALSE, 10, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Umbrella', 2, FALSE, 10, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Black Rainbow', 2, FALSE, 10, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Red Diamante', 2, FALSE, 5, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Red Holo Foil', 2, FALSE, 5, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Watering Can', 2, FALSE, 5, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Spring Training Red Foilboard', 2, FALSE, 5, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Birds', 2, FALSE, 1, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Foilfractor', 2, FALSE, 1, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'First Card', 2, FALSE, 1, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Platinum Holo Foil', 2, FALSE, 1, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Printing Plate Black', 2, FALSE, 1, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Printing Plate Cyan', 2, FALSE, 1, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Printing Plate Magenta', 2, FALSE, 1, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Yellow', 2, FALSE, 1, '');
INSERT INTO sets (release_id, set_name, set_type, is_autographed, max_serial_num, description) VALUES (1, 'Spring Training Black Foilboard', 2, FALSE, 1, '');